--- #YAML:1.0
name:                PJVM
version:             0.01_01
abstract:            Java virtual machine written in Perl
license:             mit
author:              
    - Claes Jakobsson <claesjac@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    File::Slurp:                   0
    IO::Scalar:                    0
    Object::Tiny:                  0
    Scalar::Util:                  0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
